# app相关基础信息
app:
  name: "small-website-monitor"  # 项目名称
  runType: "dev"  # 运行模式

# http服务
httpServer:
  open: true
  prod: 18888 # 端口

# user
user:
  -
    name: "admin"
    password: "123"

# jwt设置
jwt:
  secret: "small-website-monitor20230808"
  expire: 86400
