# app相关基础信息
app:
  name: "small-website-monitor"  # 项目名称
  runType: "prod"  # 运行模式

# http 服务
httpServer:
  open: true
  prod: 18888 # 端口

# user
user:
  -
    name: "admin"
    password: "123"

jwt:
  secret: "asdasd786251ashdgjdbd"
  expire: 86400